name: My First Workflow
on:
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
            echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
            echo "Current branch is ${{ github.ref }}."
            echo "My secret is ${{ secrets.MY_SECRET }}"
        shell: bash
      - name: Check out
        uses: actions/checkout@v4.1.7
      - name: Tree
        run: tree
